// <auto-generated />
using System;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Metadata;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using app_cadastro.Data;

namespace app_cadastro.Migrations
{
    [DbContext(typeof(BancoContext))]
    [Migration("20231217202029_CriandoTabelaContatos")]
    partial class CriandoTabelaContatos
    {
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .UseIdentityColumns()
                .HasAnnotation("Relational:MaxIdentifierLength", 128)
                .HasAnnotation("ProductVersion", "5.0.0");

            modelBuilder.Entity("app_cadastro.Models.AniversariantesItemUsuarioModel", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int")
                        .UseIdentityColumn();

                    b.Property<int>("Id_Aniversariantes")
                        .HasColumnType("int");

                    b.Property<int>("Id_Item")
                        .HasColumnType("int");

                    b.Property<int>("Id_Usuario")
                        .HasColumnType("int");

                    b.Property<string>("Nome_Item")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Nome_Usuario")
                        .HasColumnType("nvarchar(max)");

                    b.Property<bool>("StatusExc")
                        .HasColumnType("bit");

                    b.HasKey("Id");

                    b.ToTable("Aniversariantes_Item_Usuario");
                });

            modelBuilder.Entity("app_cadastro.Models.AniversariantesModel", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int")
                        .UseIdentityColumn();

                    b.Property<DateTime>("DataRealizacao")
                        .HasColumnType("datetime2");

                    b.Property<string>("Descricao")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Nome")
                        .HasColumnType("nvarchar(max)");

                    b.Property<bool>("StatusExc")
                        .HasColumnType("bit");

                    b.HasKey("Id");

                    b.ToTable("Aniversariantes_Do_Mes");
                });

            modelBuilder.Entity("app_cadastro.Models.Arquivos", b =>
                {
                    b.Property<int>("ID")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int")
                        .UseIdentityColumn();

                    b.Property<string>("ContentType")
                        .HasColumnType("nvarchar(max)");

                    b.Property<byte[]>("Dados")
                        .HasColumnType("varbinary(max)");

                    b.Property<DateTime>("Data_Envio")
                        .HasColumnType("datetime2");

                    b.Property<string>("Descricao")
                        .HasColumnType("nvarchar(max)");

                    b.Property<int>("Id_Cafe")
                        .HasColumnType("int");

                    b.Property<int>("Id_Usuario")
                        .HasColumnType("int");

                    b.Property<string>("NomeUsuario")
                        .HasColumnType("nvarchar(max)");

                    b.Property<bool>("StatusAprovado")
                        .HasColumnType("bit");

                    b.HasKey("ID");

                    b.ToTable("Arquivos");
                });

            modelBuilder.Entity("app_cadastro.Models.EventoItemUsuarioModel", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int")
                        .UseIdentityColumn();

                    b.Property<int>("Id_Evento")
                        .HasColumnType("int");

                    b.Property<int>("Id_Item_Evento")
                        .HasColumnType("int");

                    b.Property<int>("Id_Usuario")
                        .HasColumnType("int");

                    b.Property<string>("Nome_Item")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Nome_Usuario")
                        .HasColumnType("nvarchar(max)");

                    b.Property<bool>("StatusExc")
                        .HasColumnType("bit");

                    b.HasKey("Id");

                    b.ToTable("Evento_Item_Usuario");
                });

            modelBuilder.Entity("app_cadastro.Models.EventoModel", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int")
                        .UseIdentityColumn();

                    b.Property<DateTime>("DataEvento")
                        .HasColumnType("datetime2");

                    b.Property<string>("Descricao")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("NomeEvento")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Organizador")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<bool>("StatusExc")
                        .HasColumnType("bit");

                    b.Property<int?>("UsuarioId")
                        .HasColumnType("int")
                        .HasColumnName("UsuarioId");

                    b.HasKey("Id");

                    b.ToTable("Eventos");
                });

            modelBuilder.Entity("app_cadastro.Models.ItemAniversarioModel", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int")
                        .UseIdentityColumn();

                    b.Property<string>("Nome")
                        .HasColumnType("nvarchar(max)");

                    b.Property<bool>("StatusExc")
                        .HasColumnType("bit");

                    b.HasKey("Id");

                    b.ToTable("Item_Aniversario");
                });

            modelBuilder.Entity("app_cadastro.Models.ItemEventoModel", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int")
                        .UseIdentityColumn();

                    b.Property<int>("Id_Evento")
                        .HasColumnType("int");

                    b.Property<string>("Nome")
                        .HasColumnType("nvarchar(max)");

                    b.Property<bool>("StatusExc")
                        .HasColumnType("bit");

                    b.HasKey("Id");

                    b.ToTable("Item_Evento");
                });

            modelBuilder.Entity("app_cadastro.Models.SugestaoModel", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int")
                        .UseIdentityColumn();

                    b.Property<DateTime>("DataSugestao")
                        .HasColumnType("datetime2");

                    b.Property<string>("Descricao")
                        .HasColumnType("nvarchar(max)");

                    b.Property<bool>("StatusExc")
                        .HasColumnType("bit");

                    b.Property<string>("UsuarioSugestao")
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("Id");

                    b.ToTable("Sugestao");
                });

            modelBuilder.Entity("app_cadastro.Models.Usuarios", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int")
                        .UseIdentityColumn();

                    b.Property<DateTime>("Aniversario")
                        .HasColumnType("datetime2");

                    b.Property<int>("Celular")
                        .HasColumnType("int");

                    b.Property<string>("Email")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Nome")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<int>("Perfil")
                        .HasColumnType("int");

                    b.Property<string>("Senha")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<int?>("Setor")
                        .HasColumnType("int");

                    b.Property<bool>("StatusExc")
                        .HasColumnType("bit");

                    b.HasKey("Id");

                    b.ToTable("Usuarios");
                });

            modelBuilder.Entity("app_cadastro.Models.VaquinhaCafeModel", b =>
                {
                    b.Property<int>("Id_Vaquinha_Cafe")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int")
                        .UseIdentityColumn();

                    b.Property<string>("Chave_Pix")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Descricao")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Nome")
                        .HasColumnType("nvarchar(max)");

                    b.Property<DateTime>("Prazo_Pagamento")
                        .HasColumnType("datetime2");

                    b.Property<bool>("StatusExc")
                        .HasColumnType("bit");

                    b.HasKey("Id_Vaquinha_Cafe");

                    b.ToTable("Vaquinha_Cafe");
                });
#pragma warning restore 612, 618
        }
    }
}
